/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sapat
 */
public class MainTutorMenu_GUI extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen_GUI
     */
    public MainTutorMenu_GUI() {
        initComponents();

    }
    
    //-- Inicio Jtable 
    public static DefaultTableModel attemptInfoFunc(ResultSet rs) {
        try {
            ResultSetMetaData metaData = rs.getMetaData();
            int numberOfColumns = metaData.getColumnCount();
            Vector columnNames = new Vector();

            columnNames.addElement("ID");
            columnNames.addElement("SCORE");
            columnNames.addElement("DATA");
            columnNames.addElement("HR_CONCLUSÃO");

            Vector rows = new Vector();
            while (rs.next()) {
                Vector newRow = new Vector();
                for (int i = 1; i <= numberOfColumns; i++) {
                    newRow.addElement(rs.getObject(i));
                }
                rows.addElement(newRow);
            }
            return new DefaultTableModel(rows, columnNames);
        } catch (Exception e) {
            return null;
        }
    }

    // ---Fim Jtable
    
    //-- Inicio Jtable 
    public static DefaultTableModel clearAttemptInfoFunc() {
        try {
            DefaultTableModel model = new DefaultTableModel();

            model.addColumn("ID");
            model.addColumn("SCORE");
            model.addColumn("DATA");
            model.addColumn("HR_CONCLUSÃO");
            model.setRowCount(0);
            return model;
        } catch (Exception e) {
            return null;
        }
    }
    // ---Fim Jtable
    
    //-- Inicio Jtable 
    public static DefaultTableModel residentInfoFunc(ResultSet rs) {
        try {
            ResultSetMetaData metaData = rs.getMetaData();
            int numberOfColumns = metaData.getColumnCount();
            Vector columnNames = new Vector();

            columnNames.addElement("CPF");
            columnNames.addElement("NOME");
            columnNames.addElement("EMAIL");
            columnNames.addElement("ENDERECO");

            Vector rows = new Vector();
            while (rs.next()) {
                Vector newRow = new Vector();
                for (int i = 1; i <= numberOfColumns; i++) {
                    newRow.addElement(rs.getObject(i));
                }
                rows.addElement(newRow);
            }
            return new DefaultTableModel(rows, columnNames);
        } catch (Exception e) {

            return null;
        }
    }

    // ---Fim Jtable

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("REALHEROES?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        residentQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT r FROM Resident r");
        residentList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : residentQuery.getResultList();
        residentQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT r FROM Resident r");
        residentList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : residentQuery1.getResultList();
        jScrollPane4 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        attemptInfo = new javax.swing.JTable();
        playerScore_lbl2 = new javax.swing.JLabel();
        completionTime_txt = new javax.swing.JTextField();
        completionDate_txt = new javax.swing.JTextField();
        playerScore_lbl1 = new javax.swing.JLabel();
        exit_btn2 = new javax.swing.JButton();
        logOut_btn2 = new javax.swing.JButton();
        cpfSingUp_lbl2 = new javax.swing.JLabel();
        playerScore_lbl = new javax.swing.JLabel();
        playerScore_txt = new javax.swing.JTextField();
        cpfResidentFeedback_cb = new javax.swing.JComboBox();
        addAlterFeedback_btn = new javax.swing.JButton();
        cpfSingUp_lbl3 = new javax.swing.JLabel();
        phaseFeedback_cb = new javax.swing.JComboBox();
        cpfSingUp_lbl4 = new javax.swing.JLabel();
        attemptFeedback_cb = new javax.swing.JComboBox();
        cpfSingUp_lbl5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        feedback_txt = new javax.swing.JTextArea();
        deleteFeedback_btn = new javax.swing.JButton();
        residentsBG_lbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        exit_btn1 = new javax.swing.JButton();
        logOut_btn1 = new javax.swing.JButton();
        sendSingUp_btn = new javax.swing.JButton();
        cpfAddResident_txt = new javax.swing.JTextField();
        nameAddResident_txt = new javax.swing.JTextField();
        emailAddResident_txt = new javax.swing.JTextField();
        addressAddResident_txt = new javax.swing.JTextField();
        residentData_lbl = new javax.swing.JLabel();
        addressSingUp_lbl1 = new javax.swing.JLabel();
        emailSingUp_lbl1 = new javax.swing.JLabel();
        nameSingUp_lbl1 = new javax.swing.JLabel();
        cpfSingUp_lbl1 = new javax.swing.JLabel();
        newResidentBG_lbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        deleteAccountProfile_btn = new javax.swing.JButton();
        showPassword_btn = new javax.swing.JToggleButton();
        cpfProfile_txt = new javax.swing.JTextField();
        passwordProfile_txt = new javax.swing.JPasswordField();
        addressProfile_txt = new javax.swing.JTextField();
        emailProfile_txt = new javax.swing.JTextField();
        nameProfile_txt = new javax.swing.JTextField();
        cpfSingUp_lbl = new javax.swing.JLabel();
        nameSingUp_lbl = new javax.swing.JLabel();
        emailSingUp_lbl = new javax.swing.JLabel();
        addressSingUp_lbl = new javax.swing.JLabel();
        passwordSingUp_lbl = new javax.swing.JLabel();
        updateProfile_btn = new javax.swing.JButton();
        refreshFields_btn = new javax.swing.JButton();
        logOut_btn = new javax.swing.JButton();
        exit_btn = new javax.swing.JButton();
        profileBG_lbl = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        residentInfo = new javax.swing.JTable();
        readResident_btn = new javax.swing.JButton();
        logOut_btn3 = new javax.swing.JButton();
        exit_btn3 = new javax.swing.JButton();
        transferResident_btn = new javax.swing.JButton();
        deleteResident_btn = new javax.swing.JButton();
        updateResident_btn = new javax.swing.JButton();
        cleanFields_btn = new javax.swing.JButton();
        nameSingUp_lbl2 = new javax.swing.JLabel();
        residentName_txt = new javax.swing.JTextField();
        emailSingUp_lbl2 = new javax.swing.JLabel();
        residentEmail_txt = new javax.swing.JTextField();
        addressSingUp_lbl2 = new javax.swing.JLabel();
        residentAddress_txt = new javax.swing.JTextField();
        cpfResidentMyResidents_cb = new javax.swing.JComboBox();
        cpfSingUp_lbl6 = new javax.swing.JLabel();
        residentsBG_lbl1 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        jScrollPane4.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel2.setPreferredSize(new java.awt.Dimension(396, 704));
        jPanel2.setLayout(null);

        attemptInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(attemptInfo);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(10, 160, 380, 90);

        playerScore_lbl2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        playerScore_lbl2.setForeground(new java.awt.Color(255, 255, 255));
        playerScore_lbl2.setText("HORÁRIO:");
        jPanel2.add(playerScore_lbl2);
        playerScore_lbl2.setBounds(20, 380, 130, 30);

        completionTime_txt.setText("HORARIO DE CONCLUSAO");
        completionTime_txt.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        completionTime_txt.setEnabled(false);
        completionTime_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completionTime_txtActionPerformed(evt);
            }
        });
        jPanel2.add(completionTime_txt);
        completionTime_txt.setBounds(140, 380, 240, 30);

        completionDate_txt.setText("DATA CONCLUSÃO");
        completionDate_txt.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        completionDate_txt.setEnabled(false);
        completionDate_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completionDate_txtActionPerformed(evt);
            }
        });
        jPanel2.add(completionDate_txt);
        completionDate_txt.setBounds(140, 340, 240, 30);

        playerScore_lbl1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        playerScore_lbl1.setForeground(new java.awt.Color(255, 255, 255));
        playerScore_lbl1.setText("CONCLUSÃO:");
        jPanel2.add(playerScore_lbl1);
        playerScore_lbl1.setBounds(20, 340, 130, 30);

        exit_btn2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exit_btn2.setText("SAIR");
        exit_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(exit_btn2);
        exit_btn2.setBounds(270, 630, 110, 30);

        logOut_btn2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logOut_btn2.setText("LOGOUT");
        logOut_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(logOut_btn2);
        logOut_btn2.setBounds(270, 590, 110, 30);

        cpfSingUp_lbl2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cpfSingUp_lbl2.setForeground(new java.awt.Color(255, 255, 255));
        cpfSingUp_lbl2.setText("CPF:");
        jPanel2.add(cpfSingUp_lbl2);
        cpfSingUp_lbl2.setBounds(20, 80, 70, 30);

        playerScore_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        playerScore_lbl.setForeground(new java.awt.Color(255, 255, 255));
        playerScore_lbl.setText("SCORE:");
        jPanel2.add(playerScore_lbl);
        playerScore_lbl.setBounds(20, 300, 110, 30);

        playerScore_txt.setText("SCORE DA TENTATIVA");
        playerScore_txt.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        playerScore_txt.setEnabled(false);
        playerScore_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerScore_txtActionPerformed(evt);
            }
        });
        jPanel2.add(playerScore_txt);
        playerScore_txt.setBounds(140, 300, 240, 30);

        cpfResidentFeedback_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CLIQUE NUM ITEM PARA ATUALZAR" }));
        cpfResidentFeedback_cb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cpfResidentFeedback_cbFocusGained(evt);
            }
        });
        cpfResidentFeedback_cb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cpfResidentFeedback_cbMouseClicked(evt);
            }
        });
        cpfResidentFeedback_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfResidentFeedback_cbActionPerformed(evt);
            }
        });
        jPanel2.add(cpfResidentFeedback_cb);
        cpfResidentFeedback_cb.setBounds(120, 80, 260, 30);

        addAlterFeedback_btn.setText("ADICIONAR/ALTERAR FEEDBACK");
        addAlterFeedback_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAlterFeedback_btnActionPerformed(evt);
            }
        });
        jPanel2.add(addAlterFeedback_btn);
        addAlterFeedback_btn.setBounds(20, 530, 220, 30);

        cpfSingUp_lbl3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cpfSingUp_lbl3.setForeground(new java.awt.Color(255, 255, 255));
        cpfSingUp_lbl3.setText("FASE:");
        jPanel2.add(cpfSingUp_lbl3);
        cpfSingUp_lbl3.setBounds(20, 120, 70, 30);

        phaseFeedback_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONE A FASE" }));
        phaseFeedback_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phaseFeedback_cbActionPerformed(evt);
            }
        });
        jPanel2.add(phaseFeedback_cb);
        phaseFeedback_cb.setBounds(120, 120, 260, 30);

        cpfSingUp_lbl4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cpfSingUp_lbl4.setForeground(new java.awt.Color(255, 255, 255));
        cpfSingUp_lbl4.setText("FEEDBACK:");
        jPanel2.add(cpfSingUp_lbl4);
        cpfSingUp_lbl4.setBounds(20, 420, 110, 30);

        attemptFeedback_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONE A TENTATIVA" }));
        attemptFeedback_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attemptFeedback_cbActionPerformed(evt);
            }
        });
        jPanel2.add(attemptFeedback_cb);
        attemptFeedback_cb.setBounds(140, 260, 240, 30);

        cpfSingUp_lbl5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cpfSingUp_lbl5.setForeground(new java.awt.Color(255, 255, 255));
        cpfSingUp_lbl5.setText("TENTATIVA:");
        jPanel2.add(cpfSingUp_lbl5);
        cpfSingUp_lbl5.setBounds(20, 260, 110, 30);

        feedback_txt.setColumns(20);
        feedback_txt.setRows(5);
        feedback_txt.setText("ESCREVA SEU FEEDBACK AQUI");
        jScrollPane1.setViewportView(feedback_txt);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(140, 420, 240, 80);

        deleteFeedback_btn.setForeground(new java.awt.Color(255, 0, 0));
        deleteFeedback_btn.setText("EXCLUIR FEEDBACK");
        deleteFeedback_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFeedback_btnActionPerformed(evt);
            }
        });
        jPanel2.add(deleteFeedback_btn);
        deleteFeedback_btn.setBounds(20, 570, 220, 30);

        residentsBG_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/RealHeroesBG1.png"))); // NOI18N
        jPanel2.add(residentsBG_lbl);
        residentsBG_lbl.setBounds(0, -10, 400, 710);

        jTabbedPane1.addTab("Feedbacks", jPanel2);

        jPanel3.setLayout(null);

        exit_btn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exit_btn1.setText("SAIR");
        exit_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btn1ActionPerformed(evt);
            }
        });
        jPanel3.add(exit_btn1);
        exit_btn1.setBounds(270, 630, 110, 30);

        logOut_btn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logOut_btn1.setText("LOGOUT");
        logOut_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_btn1ActionPerformed(evt);
            }
        });
        jPanel3.add(logOut_btn1);
        logOut_btn1.setBounds(270, 590, 110, 30);

        sendSingUp_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sendSingUp_btn.setText("CADASTRAR");
        sendSingUp_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendSingUp_btnActionPerformed(evt);
            }
        });
        jPanel3.add(sendSingUp_btn);
        sendSingUp_btn.setBounds(100, 450, 200, 30);

        cpfAddResident_txt.setText("CPF");
        cpfAddResident_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfAddResident_txtActionPerformed(evt);
            }
        });
        jPanel3.add(cpfAddResident_txt);
        cpfAddResident_txt.setBounds(110, 180, 260, 30);

        nameAddResident_txt.setText("NOME COMPLETO");
        nameAddResident_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameAddResident_txtActionPerformed(evt);
            }
        });
        jPanel3.add(nameAddResident_txt);
        nameAddResident_txt.setBounds(110, 240, 260, 30);

        emailAddResident_txt.setText("EMAIL");
        jPanel3.add(emailAddResident_txt);
        emailAddResident_txt.setBounds(110, 300, 260, 30);

        addressAddResident_txt.setText("ENDERECO");
        jPanel3.add(addressAddResident_txt);
        addressAddResident_txt.setBounds(110, 360, 260, 30);

        residentData_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        residentData_lbl.setForeground(new java.awt.Color(255, 255, 255));
        residentData_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        residentData_lbl.setText("Dados do residente");
        jPanel3.add(residentData_lbl);
        residentData_lbl.setBounds(10, 110, 370, 30);

        addressSingUp_lbl1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addressSingUp_lbl1.setForeground(new java.awt.Color(255, 255, 255));
        addressSingUp_lbl1.setText("Endereco:");
        jPanel3.add(addressSingUp_lbl1);
        addressSingUp_lbl1.setBounds(10, 360, 110, 30);

        emailSingUp_lbl1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emailSingUp_lbl1.setForeground(new java.awt.Color(255, 255, 255));
        emailSingUp_lbl1.setText("Email:");
        jPanel3.add(emailSingUp_lbl1);
        emailSingUp_lbl1.setBounds(10, 300, 70, 30);

        nameSingUp_lbl1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nameSingUp_lbl1.setForeground(new java.awt.Color(255, 255, 255));
        nameSingUp_lbl1.setText("Nome:");
        jPanel3.add(nameSingUp_lbl1);
        nameSingUp_lbl1.setBounds(10, 240, 70, 30);

        cpfSingUp_lbl1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cpfSingUp_lbl1.setForeground(new java.awt.Color(255, 255, 255));
        cpfSingUp_lbl1.setText("CPF:");
        jPanel3.add(cpfSingUp_lbl1);
        cpfSingUp_lbl1.setBounds(10, 180, 70, 30);

        newResidentBG_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/RealHeroesBG5.png"))); // NOI18N
        jPanel3.add(newResidentBG_lbl);
        newResidentBG_lbl.setBounds(0, -10, 400, 710);

        jTabbedPane1.addTab("Add Residente", jPanel3);

        jPanel1.setLayout(null);

        deleteAccountProfile_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deleteAccountProfile_btn.setForeground(new java.awt.Color(255, 0, 0));
        deleteAccountProfile_btn.setText("EXCLUIR CONTA");
        deleteAccountProfile_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAccountProfile_btnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteAccountProfile_btn);
        deleteAccountProfile_btn.setBounds(120, 490, 170, 30);

        showPassword_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/eyeIcon.png"))); // NOI18N
        showPassword_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassword_btnActionPerformed(evt);
            }
        });
        jPanel1.add(showPassword_btn);
        showPassword_btn.setBounds(333, 380, 50, 30);

        cpfProfile_txt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cpfProfile_txt.setText(Controller.LoggedUser_Controller.getLoggedUser().getCpf());
        cpfProfile_txt.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        cpfProfile_txt.setEnabled(false);
        jPanel1.add(cpfProfile_txt);
        cpfProfile_txt.setBounds(110, 180, 270, 30);

        passwordProfile_txt.setText(Controller.LoggedUser_Controller.getLoggedUser().getPassword());
        jPanel1.add(passwordProfile_txt);
        passwordProfile_txt.setBounds(110, 380, 220, 30);

        addressProfile_txt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addressProfile_txt.setText(Controller.LoggedUser_Controller.getLoggedUser().getAddress());
        jPanel1.add(addressProfile_txt);
        addressProfile_txt.setBounds(110, 330, 270, 30);

        emailProfile_txt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailProfile_txt.setText(Controller.LoggedUser_Controller.getLoggedUser().getEmail());
        jPanel1.add(emailProfile_txt);
        emailProfile_txt.setBounds(110, 280, 270, 30);

        nameProfile_txt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameProfile_txt.setText(Controller.LoggedUser_Controller.getLoggedUser().getName());
        jPanel1.add(nameProfile_txt);
        nameProfile_txt.setBounds(110, 230, 270, 30);

        cpfSingUp_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cpfSingUp_lbl.setForeground(new java.awt.Color(255, 255, 255));
        cpfSingUp_lbl.setText("CPF:");
        jPanel1.add(cpfSingUp_lbl);
        cpfSingUp_lbl.setBounds(10, 180, 70, 30);

        nameSingUp_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nameSingUp_lbl.setForeground(new java.awt.Color(255, 255, 255));
        nameSingUp_lbl.setText("Nome:");
        jPanel1.add(nameSingUp_lbl);
        nameSingUp_lbl.setBounds(10, 230, 70, 30);

        emailSingUp_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emailSingUp_lbl.setForeground(new java.awt.Color(255, 255, 255));
        emailSingUp_lbl.setText("Email:");
        jPanel1.add(emailSingUp_lbl);
        emailSingUp_lbl.setBounds(10, 280, 70, 30);

        addressSingUp_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addressSingUp_lbl.setForeground(new java.awt.Color(255, 255, 255));
        addressSingUp_lbl.setText("Endereco:");
        jPanel1.add(addressSingUp_lbl);
        addressSingUp_lbl.setBounds(10, 330, 110, 30);

        passwordSingUp_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        passwordSingUp_lbl.setForeground(new java.awt.Color(255, 255, 255));
        passwordSingUp_lbl.setText("Senha:");
        jPanel1.add(passwordSingUp_lbl);
        passwordSingUp_lbl.setBounds(10, 380, 70, 30);

        updateProfile_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateProfile_btn.setText("ALTERAR");
        updateProfile_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProfile_btnActionPerformed(evt);
            }
        });
        jPanel1.add(updateProfile_btn);
        updateProfile_btn.setBounds(30, 440, 170, 30);

        refreshFields_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        refreshFields_btn.setText("RESETAR CAMPOS");
        refreshFields_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshFields_btnActionPerformed(evt);
            }
        });
        jPanel1.add(refreshFields_btn);
        refreshFields_btn.setBounds(210, 440, 170, 30);

        logOut_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logOut_btn.setText("LOGOUT");
        logOut_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_btnActionPerformed(evt);
            }
        });
        jPanel1.add(logOut_btn);
        logOut_btn.setBounds(270, 590, 110, 30);

        exit_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exit_btn.setText("SAIR");
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(exit_btn);
        exit_btn.setBounds(270, 630, 110, 30);

        profileBG_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/RealHeroesBG6.png"))); // NOI18N
        jPanel1.add(profileBG_lbl);
        profileBG_lbl.setBounds(0, -10, 400, 710);

        jTabbedPane1.addTab("Perfil", jPanel1);

        jPanel4.setLayout(null);

        residentInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(residentInfo);

        jPanel4.add(jScrollPane5);
        jScrollPane5.setBounds(10, 70, 370, 120);

        readResident_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        readResident_btn.setText("CONSULTAR");
        readResident_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readResident_btnActionPerformed(evt);
            }
        });
        jPanel4.add(readResident_btn);
        readResident_btn.setBounds(40, 390, 320, 30);

        logOut_btn3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logOut_btn3.setText("LOGOUT");
        logOut_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_btn3ActionPerformed(evt);
            }
        });
        jPanel4.add(logOut_btn3);
        logOut_btn3.setBounds(270, 590, 110, 30);

        exit_btn3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exit_btn3.setText("SAIR");
        exit_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btn3ActionPerformed(evt);
            }
        });
        jPanel4.add(exit_btn3);
        exit_btn3.setBounds(270, 630, 110, 30);

        transferResident_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        transferResident_btn.setForeground(new java.awt.Color(255, 0, 0));
        transferResident_btn.setText("TRANSFERIR RESIDENTE");
        transferResident_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferResident_btnActionPerformed(evt);
            }
        });
        jPanel4.add(transferResident_btn);
        transferResident_btn.setBounds(40, 510, 320, 30);

        deleteResident_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deleteResident_btn.setForeground(new java.awt.Color(255, 0, 0));
        deleteResident_btn.setText("EXCLUIR RESIDENTE");
        deleteResident_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteResident_btnActionPerformed(evt);
            }
        });
        jPanel4.add(deleteResident_btn);
        deleteResident_btn.setBounds(40, 550, 320, 30);

        updateResident_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateResident_btn.setText("ALTERAR INFORMACOES");
        updateResident_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateResident_btnActionPerformed(evt);
            }
        });
        jPanel4.add(updateResident_btn);
        updateResident_btn.setBounds(40, 430, 320, 30);

        cleanFields_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cleanFields_btn.setText("LIMPAR CAMPOS");
        cleanFields_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanFields_btnActionPerformed(evt);
            }
        });
        jPanel4.add(cleanFields_btn);
        cleanFields_btn.setBounds(40, 470, 320, 30);

        nameSingUp_lbl2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nameSingUp_lbl2.setForeground(new java.awt.Color(255, 255, 255));
        nameSingUp_lbl2.setText("Nome:");
        jPanel4.add(nameSingUp_lbl2);
        nameSingUp_lbl2.setBounds(10, 250, 70, 30);

        residentName_txt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel4.add(residentName_txt);
        residentName_txt.setBounds(110, 250, 270, 30);

        emailSingUp_lbl2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emailSingUp_lbl2.setForeground(new java.awt.Color(255, 255, 255));
        emailSingUp_lbl2.setText("Email:");
        jPanel4.add(emailSingUp_lbl2);
        emailSingUp_lbl2.setBounds(10, 300, 70, 30);

        residentEmail_txt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel4.add(residentEmail_txt);
        residentEmail_txt.setBounds(110, 300, 270, 30);

        addressSingUp_lbl2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addressSingUp_lbl2.setForeground(new java.awt.Color(255, 255, 255));
        addressSingUp_lbl2.setText("Endereco:");
        jPanel4.add(addressSingUp_lbl2);
        addressSingUp_lbl2.setBounds(10, 350, 110, 30);

        residentAddress_txt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel4.add(residentAddress_txt);
        residentAddress_txt.setBounds(110, 350, 270, 30);

        cpfResidentMyResidents_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CLIQUE NUM ITEM PARA ATUALZAR" }));
        cpfResidentMyResidents_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cpfResidentMyResidents_cbItemStateChanged(evt);
            }
        });
        cpfResidentMyResidents_cb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cpfResidentMyResidents_cbFocusGained(evt);
            }
        });
        cpfResidentMyResidents_cb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cpfResidentMyResidents_cbMouseClicked(evt);
            }
        });
        cpfResidentMyResidents_cb.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                cpfResidentMyResidents_cbCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        cpfResidentMyResidents_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfResidentMyResidents_cbActionPerformed(evt);
            }
        });
        jPanel4.add(cpfResidentMyResidents_cb);
        cpfResidentMyResidents_cb.setBounds(110, 200, 270, 30);

        cpfSingUp_lbl6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cpfSingUp_lbl6.setForeground(new java.awt.Color(255, 255, 255));
        cpfSingUp_lbl6.setText("CPF:");
        jPanel4.add(cpfSingUp_lbl6);
        cpfSingUp_lbl6.setBounds(10, 200, 70, 30);

        residentsBG_lbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/RealHeroesBG2.png"))); // NOI18N
        jPanel4.add(residentsBG_lbl1);
        residentsBG_lbl1.setBounds(0, -10, 400, 710);

        jTabbedPane1.addTab("Meus Residentes", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(396, 704));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        Model.RefreshFuncs_DAO.refreshResidentCpfOptions();
        Model.RefreshFuncs_DAO.refreshMyResidentsTable();
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        Model.Funcs_DAO.exit();
    }//GEN-LAST:event_exit_btnActionPerformed

    private void logOut_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_btnActionPerformed
        Controller.LoggedUser_Controller.logout();
        JOptionPane.showMessageDialog(null, "Logout realizado com sucesso! Ate mais!");
        Model.Funcs_DAO.changeScreen(this, new SetUp_GUI());
    }//GEN-LAST:event_logOut_btnActionPerformed

    private void refreshFields_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshFields_btnActionPerformed
        Model.Funcs_DAO.profileRefresh();
    }//GEN-LAST:event_refreshFields_btnActionPerformed

    private void updateProfile_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProfile_btnActionPerformed
        if (Model.Funcs_DAO.updateConfirmation()) {
            String cpf = cpfProfile_txt.getText();
            String name = nameProfile_txt.getText();
            String email = emailProfile_txt.getText();
            String address = addressProfile_txt.getText();
            String password = passwordProfile_txt.getText();
            if (Model.TutorFuncs_DAO.updateTutor(cpf, name, email, address, password)) {
                Model.Funcs_DAO.profileRefresh();
            }
        }
    }//GEN-LAST:event_updateProfile_btnActionPerformed

    private void showPassword_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassword_btnActionPerformed
        if (showPassword_btn.isSelected()) {
            // Mostrar os caracteres reais
            passwordProfile_txt.setEchoChar('\0');
        } else {
            // Ocultar os caracteres reais
            passwordProfile_txt.setEchoChar('\u25cf');
        }
    }//GEN-LAST:event_showPassword_btnActionPerformed

    private void deleteAccountProfile_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAccountProfile_btnActionPerformed
        if (Model.Funcs_DAO.deleteAccountConfirmation()) {
            if (Model.TutorFuncs_DAO.deleteAccount()) {
                Controller.LoggedUser_Controller.logout();
                Model.Funcs_DAO.changeScreen(this, new SetUp_GUI());
            }
        }
    }//GEN-LAST:event_deleteAccountProfile_btnActionPerformed

    private void nameAddResident_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameAddResident_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameAddResident_txtActionPerformed

    private void cpfAddResident_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfAddResident_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfAddResident_txtActionPerformed

    private void sendSingUp_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendSingUp_btnActionPerformed
        String cpf = cpfAddResident_txt.getText();
        String name = nameAddResident_txt.getText();
        String email = emailAddResident_txt.getText();
        String address = addressAddResident_txt.getText();
        Model.ResidentFuncs_DAO.addResident(cpf, name, email, address, Controller.LoggedUser_Controller.getLoggedUser().getCpf());
        //Model.ResidentFuncs_DAO.refreshFeedbackTable();
        Model.RefreshFuncs_DAO.refreshResidentCpfOptions();
        Model.RefreshFuncs_DAO.refreshMyResidentsTable();
    }//GEN-LAST:event_sendSingUp_btnActionPerformed

    private void logOut_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_btn1ActionPerformed
        Controller.LoggedUser_Controller.logout();
        JOptionPane.showMessageDialog(null, "Logout realizado com sucesso! Ate mais!");
        Model.Funcs_DAO.changeScreen(this, new SetUp_GUI());
    }//GEN-LAST:event_logOut_btn1ActionPerformed

    private void exit_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btn1ActionPerformed
        Model.Funcs_DAO.exit();
    }//GEN-LAST:event_exit_btn1ActionPerformed

    private void deleteFeedback_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFeedback_btnActionPerformed
        Model.AttemptFuncs_DAO.deleteAttemptFeedback();
    }//GEN-LAST:event_deleteFeedback_btnActionPerformed

    private void attemptFeedback_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attemptFeedback_cbActionPerformed
        String selectedPhase = (String) phaseFeedback_cb.getSelectedItem();
        String selectedAttempt = (String) attemptFeedback_cb.getSelectedItem();
        Model.AttemptFuncs_DAO.showSelectedAttemptInfo(selectedPhase, selectedAttempt);
    }//GEN-LAST:event_attemptFeedback_cbActionPerformed

    private void phaseFeedback_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phaseFeedback_cbActionPerformed
        //if (Model.RefreshFuncs_DAO.refreshAttemptOptions()) {
        //    Model.RefreshFuncs_DAO.refreshFeedbackTable();
        //}

        String selectedPhase = String.valueOf(phaseFeedback_cb.getSelectedItem());
        String selectedCpf = String.valueOf(cpfResidentFeedback_cb.getSelectedItem());
        Model.RefreshFuncs_DAO.refreshAttemptOptions(selectedPhase, selectedCpf);
        Model.RefreshFuncs_DAO.refreshFeedbackTable(selectedPhase, selectedCpf); //ESSA FUNÇÃO TEM QUE VERIFICAR SE O RETORNO DA QUERY É VAZIO, SE FOR VAZIO, PREENCHE A TABLE A COM NADA. SE NAO, PREENCHE NORMAL
        Model.Funcs_DAO.resetFeedbackFields();
        
    }//GEN-LAST:event_phaseFeedback_cbActionPerformed

    private void addAlterFeedback_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAlterFeedback_btnActionPerformed
        String feedbackText = feedback_txt.getText();
        Model.AttemptFuncs_DAO.updateAttemptFeedback(feedbackText);
    }//GEN-LAST:event_addAlterFeedback_btnActionPerformed

    private void cpfResidentFeedback_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfResidentFeedback_cbActionPerformed
        //Model.RefreshFuncs_DAO.refreshPhaseOptions();
        //Model.Funcs_DAO.cleanFeedbackFields();
        //Model.RefreshFuncs_DAO.refreshFeedbackTable();
        
        
        String selectedCpf = (String) cpfResidentFeedback_cb.getSelectedItem();
        Model.RefreshFuncs_DAO.refreshPhaseOptions(selectedCpf);
        Model.Funcs_DAO.resetFeedbackFields();
    }//GEN-LAST:event_cpfResidentFeedback_cbActionPerformed

    private void cpfResidentFeedback_cbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cpfResidentFeedback_cbMouseClicked

    }//GEN-LAST:event_cpfResidentFeedback_cbMouseClicked

    private void cpfResidentFeedback_cbFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfResidentFeedback_cbFocusGained

    }//GEN-LAST:event_cpfResidentFeedback_cbFocusGained

    private void logOut_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_btn2ActionPerformed
        Controller.LoggedUser_Controller.logout();
        JOptionPane.showMessageDialog(null, "Logout realizado com sucesso! Ate mais!");
        Model.Funcs_DAO.changeScreen(this, new SetUp_GUI());
    }//GEN-LAST:event_logOut_btn2ActionPerformed

    private void exit_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btn2ActionPerformed
        Model.Funcs_DAO.exit();
    }//GEN-LAST:event_exit_btn2ActionPerformed

    private void completionDate_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completionDate_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_completionDate_txtActionPerformed

    private void completionTime_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completionTime_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_completionTime_txtActionPerformed

    private void cpfResidentMyResidents_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfResidentMyResidents_cbActionPerformed
        Model.Funcs_DAO.cleanMyResidentsFields();
    }//GEN-LAST:event_cpfResidentMyResidents_cbActionPerformed

    private void cpfResidentMyResidents_cbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cpfResidentMyResidents_cbMouseClicked
        
    }//GEN-LAST:event_cpfResidentMyResidents_cbMouseClicked

    private void cpfResidentMyResidents_cbFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfResidentMyResidents_cbFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfResidentMyResidents_cbFocusGained

    private void deleteResident_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteResident_btnActionPerformed
        String residentCpf = String.valueOf(cpfResidentMyResidents_cb.getSelectedItem()); 
        if (Model.Funcs_DAO.deleteAccountConfirmation()) {
            Model.ResidentFuncs_DAO.deleteResident(residentCpf);
            Model.RefreshFuncs_DAO.refreshResidentCpfOptions();
            Model.RefreshFuncs_DAO.refreshMyResidentsTable();
        }
    }//GEN-LAST:event_deleteResident_btnActionPerformed

    private void updateResident_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateResident_btnActionPerformed
       if (Model.Funcs_DAO.updateConfirmation()) {
            String residentCpf = String.valueOf(cpfResidentMyResidents_cb.getSelectedItem());
            String residentName = String.valueOf(residentName_txt.getText()); 
            String residentEmail = String.valueOf(residentEmail_txt.getText()); 
            String residentAddress = String.valueOf(residentAddress_txt.getText()); 
            if (Model.ResidentFuncs_DAO.updateResidentInfo(residentCpf, residentName, residentEmail, residentAddress)) {
                Model.RefreshFuncs_DAO.refreshMyResidentsTable();
                Model.Funcs_DAO.cleanMyResidentsFields();
            }
        }
    }//GEN-LAST:event_updateResident_btnActionPerformed

    private void cleanFields_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanFields_btnActionPerformed
        Model.Funcs_DAO.cleanMyResidentsFields();
    }//GEN-LAST:event_cleanFields_btnActionPerformed

    private void transferResident_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferResident_btnActionPerformed
        String tutorCpf = JOptionPane.showInputDialog(null, "Digite o CPF do tutor a receber o residente: ");
        String residentCpf = String.valueOf(cpfResidentMyResidents_cb.getSelectedItem()); 
        if (Model.ResidentFuncs_DAO.transferResident(residentCpf, tutorCpf)) {
            Model.RefreshFuncs_DAO.refreshResidentCpfOptions();
            Model.RefreshFuncs_DAO.refreshMyResidentsTable();
        }
    }//GEN-LAST:event_transferResident_btnActionPerformed

    private void logOut_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_btn3ActionPerformed
        Controller.LoggedUser_Controller.logout();
        JOptionPane.showMessageDialog(null, "Logout realizado com sucesso! Ate mais!");
        Model.Funcs_DAO.changeScreen(this, new SetUp_GUI());
    }//GEN-LAST:event_logOut_btn3ActionPerformed

    private void exit_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btn3ActionPerformed
        Model.Funcs_DAO.exit();
    }//GEN-LAST:event_exit_btn3ActionPerformed

    private void cpfResidentMyResidents_cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cpfResidentMyResidents_cbItemStateChanged
        
    }//GEN-LAST:event_cpfResidentMyResidents_cbItemStateChanged

    private void cpfResidentMyResidents_cbCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cpfResidentMyResidents_cbCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfResidentMyResidents_cbCaretPositionChanged

    private void readResident_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readResident_btnActionPerformed
        String residentCpf = String.valueOf(cpfResidentMyResidents_cb.getSelectedItem());
        Model.ResidentFuncs_DAO.readResident(residentCpf);
    }//GEN-LAST:event_readResident_btnActionPerformed

    private void playerScore_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerScore_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerScore_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainTutorMenu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainTutorMenu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainTutorMenu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainTutorMenu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainTutorMenu_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAlterFeedback_btn;
    public static javax.swing.JTextField addressAddResident_txt;
    public static javax.swing.JTextField addressProfile_txt;
    private javax.swing.JLabel addressSingUp_lbl;
    private javax.swing.JLabel addressSingUp_lbl1;
    private javax.swing.JLabel addressSingUp_lbl2;
    public static javax.swing.JComboBox attemptFeedback_cb;
    public static javax.swing.JTable attemptInfo;
    public static javax.swing.JButton cleanFields_btn;
    public static javax.swing.JTextField completionDate_txt;
    public static javax.swing.JTextField completionTime_txt;
    public static javax.swing.JTextField cpfAddResident_txt;
    public static javax.swing.JTextField cpfProfile_txt;
    public static javax.swing.JComboBox cpfResidentFeedback_cb;
    public static javax.swing.JComboBox cpfResidentMyResidents_cb;
    private javax.swing.JLabel cpfSingUp_lbl;
    private javax.swing.JLabel cpfSingUp_lbl1;
    private javax.swing.JLabel cpfSingUp_lbl2;
    private javax.swing.JLabel cpfSingUp_lbl3;
    private javax.swing.JLabel cpfSingUp_lbl4;
    private javax.swing.JLabel cpfSingUp_lbl5;
    private javax.swing.JLabel cpfSingUp_lbl6;
    public static javax.swing.JButton deleteAccountProfile_btn;
    private javax.swing.JButton deleteFeedback_btn;
    public static javax.swing.JButton deleteResident_btn;
    public static javax.swing.JTextField emailAddResident_txt;
    public static javax.swing.JTextField emailProfile_txt;
    private javax.swing.JLabel emailSingUp_lbl;
    private javax.swing.JLabel emailSingUp_lbl1;
    private javax.swing.JLabel emailSingUp_lbl2;
    private javax.persistence.EntityManager entityManager;
    public static javax.swing.JButton exit_btn;
    public static javax.swing.JButton exit_btn1;
    public static javax.swing.JButton exit_btn2;
    public static javax.swing.JButton exit_btn3;
    public static javax.swing.JTextArea feedback_txt;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton jToggleButton1;
    public static javax.swing.JButton logOut_btn;
    public static javax.swing.JButton logOut_btn1;
    public static javax.swing.JButton logOut_btn2;
    public static javax.swing.JButton logOut_btn3;
    public static javax.swing.JTextField nameAddResident_txt;
    public static javax.swing.JTextField nameProfile_txt;
    private javax.swing.JLabel nameSingUp_lbl;
    private javax.swing.JLabel nameSingUp_lbl1;
    private javax.swing.JLabel nameSingUp_lbl2;
    private javax.swing.JLabel newResidentBG_lbl;
    public static javax.swing.JPasswordField passwordProfile_txt;
    private javax.swing.JLabel passwordSingUp_lbl;
    public static javax.swing.JComboBox phaseFeedback_cb;
    private javax.swing.JLabel playerScore_lbl;
    private javax.swing.JLabel playerScore_lbl1;
    private javax.swing.JLabel playerScore_lbl2;
    public static javax.swing.JTextField playerScore_txt;
    private javax.swing.JLabel profileBG_lbl;
    public static javax.swing.JButton readResident_btn;
    public static javax.swing.JButton refreshFields_btn;
    public static javax.swing.JTextField residentAddress_txt;
    private javax.swing.JLabel residentData_lbl;
    public static javax.swing.JTextField residentEmail_txt;
    public static javax.swing.JTable residentInfo;
    private java.util.List<View.Resident> residentList;
    private java.util.List<View.Resident> residentList1;
    public static javax.swing.JTextField residentName_txt;
    private javax.persistence.Query residentQuery;
    private javax.persistence.Query residentQuery1;
    private javax.swing.JLabel residentsBG_lbl;
    private javax.swing.JLabel residentsBG_lbl1;
    public static javax.swing.JButton sendSingUp_btn;
    private javax.swing.JToggleButton showPassword_btn;
    public static javax.swing.JButton transferResident_btn;
    public static javax.swing.JButton updateProfile_btn;
    public static javax.swing.JButton updateResident_btn;
    // End of variables declaration//GEN-END:variables
}
