/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author labsfiap
 */
public class MainResidentMenu_GUI extends javax.swing.JFrame {

    public static TableModel deviceInfo(ResultSet rs) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form MainResidentMenu_GUI
     */
    public MainResidentMenu_GUI() {
        initComponents();
    }
    public static DefaultTableModel deviceInfoFunc(ResultSet rs) {
        try {
            ResultSetMetaData metaData = rs.getMetaData();
            int numberOfColumns = metaData.getColumnCount();
            Vector columnNames = new Vector();

            columnNames.addElement("IDdevice");
            columnNames.addElement("Description");
            columnNames.addElement("Marca");

            Vector rows = new Vector();
            while (rs.next()) {
                Vector newRow = new Vector();
                for (int i = 1; i <= numberOfColumns; i++) {
                    newRow.addElement(rs.getObject(i));
                }
                rows.addElement(newRow);
            }
            return new DefaultTableModel(rows, columnNames);
        } catch (Exception e) {
            return null;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("realheroes?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        deviceQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT d FROM Device d");
        deviceList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : deviceQuery.getResultList();
        entityManager0 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("REALHEROES?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        deviceQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT d FROM Device d");
        deviceList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : deviceQuery1.getResultList();
        deviceQuery2 = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT d FROM Device d");
        deviceList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : deviceQuery2.getResultList();
        deviceQuery3 = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT d FROM Device d");
        deviceList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : deviceQuery3.getResultList();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        deviceInfo = new javax.swing.JTable();
        searchDevices_btn = new javax.swing.JButton();
        idDevice_cb = new javax.swing.JComboBox();
        idDispositivo_lbl = new javax.swing.JLabel();
        playerScore_lbl = new javax.swing.JLabel();
        brand_lbl = new javax.swing.JLabel();
        brand_txt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        deviceDescription_txt = new javax.swing.JTextArea();
        brand_lbl1 = new javax.swing.JLabel();
        dataRt_txt = new javax.swing.JTextField();
        reserveDevice_btn = new javax.swing.JButton();
        logOut_btn2 = new javax.swing.JButton();
        exit_btn2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        logOut_btn3 = new javax.swing.JButton();
        exit_btn3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, deviceList3, deviceInfo);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${IDdevice}"));
        columnBinding.setColumnName("IDdevice");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${description}"));
        columnBinding.setColumnName("Description");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${marca}"));
        columnBinding.setColumnName("Marca");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(deviceInfo);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 90, 390, 90);

        searchDevices_btn.setText("Buscar dispositivos disponíveis");
        searchDevices_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDevices_btnActionPerformed(evt);
            }
        });
        jPanel1.add(searchDevices_btn);
        searchDevices_btn.setBounds(10, 190, 370, 23);

        idDevice_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONE O DISPOSITIVO DESEJADO" }));
        idDevice_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idDevice_cbActionPerformed(evt);
            }
        });
        jPanel1.add(idDevice_cb);
        idDevice_cb.setBounds(150, 230, 230, 30);

        idDispositivo_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        idDispositivo_lbl.setForeground(new java.awt.Color(255, 255, 255));
        idDispositivo_lbl.setText("ID Dispositivo:");
        jPanel1.add(idDispositivo_lbl);
        idDispositivo_lbl.setBounds(10, 230, 150, 30);

        playerScore_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        playerScore_lbl.setForeground(new java.awt.Color(255, 255, 255));
        playerScore_lbl.setText("Descrição:");
        jPanel1.add(playerScore_lbl);
        playerScore_lbl.setBounds(10, 270, 110, 30);

        brand_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        brand_lbl.setForeground(new java.awt.Color(255, 255, 255));
        brand_lbl.setText("MARCA:");
        jPanel1.add(brand_lbl);
        brand_lbl.setBounds(10, 370, 130, 30);

        brand_txt.setText("MARCA DO DISPOSITIVO");
        brand_txt.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        brand_txt.setEnabled(false);
        brand_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brand_txtActionPerformed(evt);
            }
        });
        jPanel1.add(brand_txt);
        brand_txt.setBounds(150, 370, 230, 30);

        deviceDescription_txt.setEditable(false);
        deviceDescription_txt.setColumns(20);
        deviceDescription_txt.setRows(5);
        deviceDescription_txt.setText("DESCRIÇÂO");
        deviceDescription_txt.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        jScrollPane2.setViewportView(deviceDescription_txt);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(150, 270, 230, 80);

        brand_lbl1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        brand_lbl1.setForeground(new java.awt.Color(255, 255, 255));
        brand_lbl1.setText("DATA PARA RETIRAR:");
        jPanel1.add(brand_lbl1);
        brand_lbl1.setBounds(10, 420, 200, 30);

        dataRt_txt.setText("AAAA-MM-DD");
        dataRt_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataRt_txtActionPerformed(evt);
            }
        });
        jPanel1.add(dataRt_txt);
        dataRt_txt.setBounds(290, 420, 90, 30);

        reserveDevice_btn.setText("Reservar Dispositivo");
        reserveDevice_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveDevice_btnActionPerformed(evt);
            }
        });
        jPanel1.add(reserveDevice_btn);
        reserveDevice_btn.setBounds(220, 470, 160, 40);

        logOut_btn2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logOut_btn2.setText("LOGOUT");
        logOut_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(logOut_btn2);
        logOut_btn2.setBounds(270, 590, 110, 30);

        exit_btn2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exit_btn2.setText("SAIR");
        exit_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(exit_btn2);
        exit_btn2.setBounds(270, 630, 110, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/RealHeroesBG4.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -20, 390, 740);

        jTabbedPane1.addTab("Reservar Óculos", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Visualizar Feedbacks", jPanel2);

        jPanel3.setLayout(null);

        logOut_btn3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logOut_btn3.setText("LOGOUT");
        logOut_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_btn3ActionPerformed(evt);
            }
        });
        jPanel3.add(logOut_btn3);
        logOut_btn3.setBounds(270, 590, 110, 30);

        exit_btn3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exit_btn3.setText("SAIR");
        exit_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btn3ActionPerformed(evt);
            }
        });
        jPanel3.add(exit_btn3);
        exit_btn3.setBounds(270, 630, 110, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/RealHeroesBG3.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(-1, -10, 390, 720);

        jTabbedPane1.addTab("Perfil", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        bindingGroup.bind();

        setSize(new java.awt.Dimension(396, 704));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void brand_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brand_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brand_txtActionPerformed

    private void dataRt_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataRt_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataRt_txtActionPerformed

    private void searchDevices_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDevices_btnActionPerformed
        Model.DeviceFuncs_DAO.getAvaiableDevices();
        Model.DeviceFuncs_DAO.setDeviceIds();
    }//GEN-LAST:event_searchDevices_btnActionPerformed

    private void idDevice_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idDevice_cbActionPerformed
        Integer selectedID = (Integer) idDevice_cb.getSelectedItem();
        Model.DeviceFuncs_DAO.showSelectedDeviceInfo(String.valueOf(selectedID));
    }//GEN-LAST:event_idDevice_cbActionPerformed

    private void reserveDevice_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveDevice_btnActionPerformed
        // Verifique se a JComboBox foi inicializada
    if (idDevice_cb == null) {
        System.out.println("JComboBox idDevice_cb não foi inicializada.");
        return;
    }

    // Verifique se há um item selecionado
    Integer selectedID = (Integer) idDevice_cb.getSelectedItem();
    if (selectedID == null) {
        System.out.println("Nenhum dispositivo foi selecionado.");
        return;
    }

    // Verifique o campo de texto da data
    if (dataRt_txt == null) {
        System.out.println("Campo de texto dataRt_txt não foi inicializado.");
        return;
    }

    String selectedDataRt = dataRt_txt.getText();
    if (selectedDataRt.isEmpty()) {
        System.out.println("A data de reserva não foi inserida.");
        return;
    }

    // Verifique se o usuário logado está definido
    if (Controller.LoggedUser_Controller.getLoggedUser() == null) {
        System.out.println("Usuário não está logado.");
        return;
    }

    String selectedCPF = Controller.LoggedUser_Controller.getLoggedUser().getCpf();

    // Agora podemos chamar a função para reservar o dispositivo
    Model.DeviceFuncs_DAO.reserveDevice(selectedID, selectedCPF, selectedDataRt);
    }//GEN-LAST:event_reserveDevice_btnActionPerformed

    private void logOut_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_btn2ActionPerformed
        Controller.LoggedUser_Controller.logout();
        JOptionPane.showMessageDialog(null, "Logout realizado com sucesso! Ate mais!");
        Model.Funcs_DAO.changeScreen(this, new SetUp_GUI());
    }//GEN-LAST:event_logOut_btn2ActionPerformed

    private void exit_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btn2ActionPerformed
        Model.Funcs_DAO.exit();
    }//GEN-LAST:event_exit_btn2ActionPerformed

    private void logOut_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_btn3ActionPerformed
        Controller.LoggedUser_Controller.logout();
        JOptionPane.showMessageDialog(null, "Logout realizado com sucesso! Ate mais!");
        Model.Funcs_DAO.changeScreen(this, new SetUp_GUI());
    }//GEN-LAST:event_logOut_btn3ActionPerformed

    private void exit_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btn3ActionPerformed
        Model.Funcs_DAO.exit();
    }//GEN-LAST:event_exit_btn3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainResidentMenu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainResidentMenu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainResidentMenu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainResidentMenu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainResidentMenu_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brand_lbl;
    private javax.swing.JLabel brand_lbl1;
    public static javax.swing.JTextField brand_txt;
    public static javax.swing.JTextField dataRt_txt;
    public static javax.swing.JTextArea deviceDescription_txt;
    public static javax.swing.JTable deviceInfo;
    private java.util.List<View.Device> deviceList;
    private java.util.List<View.Device> deviceList1;
    private java.util.List<View.Device> deviceList2;
    private java.util.List<View.Device> deviceList3;
    private javax.persistence.Query deviceQuery;
    private javax.persistence.Query deviceQuery1;
    private javax.persistence.Query deviceQuery2;
    private javax.persistence.Query deviceQuery3;
    private javax.persistence.EntityManager entityManager;
    private javax.persistence.EntityManager entityManager0;
    public static javax.swing.JButton exit_btn2;
    public static javax.swing.JButton exit_btn3;
    public static javax.swing.JComboBox idDevice_cb;
    private javax.swing.JLabel idDispositivo_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JButton logOut_btn2;
    public static javax.swing.JButton logOut_btn3;
    private javax.swing.JLabel playerScore_lbl;
    private javax.swing.JButton reserveDevice_btn;
    private javax.swing.JButton searchDevices_btn;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
