/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author sapat
 */
public class SetUp_GUI extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen_GUI
     */
    public SetUp_GUI() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        showPassword_btn = new javax.swing.JToggleButton();
        exit_btn = new javax.swing.JButton();
        passwordLogin_txt = new javax.swing.JPasswordField();
        sendLogin_btn = new javax.swing.JButton();
        passwordLogin_lbl = new javax.swing.JLabel();
        cpfLogin_txt = new javax.swing.JTextField();
        cpfLogin_lbl = new javax.swing.JLabel();
        setUpBG_lbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        passwordSingUp_lbl = new javax.swing.JLabel();
        addressSingUp_lbl = new javax.swing.JLabel();
        emailSingUp_lbl = new javax.swing.JLabel();
        cpfSingUp_lbl = new javax.swing.JLabel();
        nameSingUp_lbl = new javax.swing.JLabel();
        showPassword_btn1 = new javax.swing.JToggleButton();
        sendSingUp_btn = new javax.swing.JButton();
        exit_btn1 = new javax.swing.JButton();
        nameSignUp_txt = new javax.swing.JTextField();
        passwordSignUp_txt = new javax.swing.JPasswordField();
        addressSignUp_txt = new javax.swing.JTextField();
        emailSignUp_txt = new javax.swing.JTextField();
        cpfSignUp_txt = new javax.swing.JTextField();
        setUpBG_lbl1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setPreferredSize(new java.awt.Dimension(396, 704));
        jPanel2.setLayout(null);

        showPassword_btn.setBackground(new java.awt.Color(255, 255, 255));
        showPassword_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/eyeIcon.png"))); // NOI18N
        showPassword_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassword_btnActionPerformed(evt);
            }
        });
        jPanel2.add(showPassword_btn);
        showPassword_btn.setBounds(320, 310, 60, 30);

        exit_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exit_btn.setText("SAIR");
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });
        jPanel2.add(exit_btn);
        exit_btn.setBounds(270, 630, 110, 30);

        passwordLogin_txt.setText("SENHA");
        passwordLogin_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordLogin_txtActionPerformed(evt);
            }
        });
        jPanel2.add(passwordLogin_txt);
        passwordLogin_txt.setBounds(110, 310, 200, 30);

        sendLogin_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sendLogin_btn.setText("LOGAR");
        sendLogin_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendLogin_btnActionPerformed(evt);
            }
        });
        jPanel2.add(sendLogin_btn);
        sendLogin_btn.setBounds(100, 370, 200, 30);

        passwordLogin_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        passwordLogin_lbl.setForeground(new java.awt.Color(255, 255, 255));
        passwordLogin_lbl.setText("Senha:");
        jPanel2.add(passwordLogin_lbl);
        passwordLogin_lbl.setBounds(10, 310, 70, 30);

        cpfLogin_txt.setText("CPF");
        jPanel2.add(cpfLogin_txt);
        cpfLogin_txt.setBounds(110, 260, 270, 30);

        cpfLogin_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cpfLogin_lbl.setForeground(new java.awt.Color(255, 255, 255));
        cpfLogin_lbl.setText("CPF:");
        jPanel2.add(cpfLogin_lbl);
        cpfLogin_lbl.setBounds(10, 260, 70, 30);

        setUpBG_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/SplashScreenRealHeroes2.png"))); // NOI18N
        jPanel2.add(setUpBG_lbl);
        setUpBG_lbl.setBounds(0, -10, 400, 700);

        jTabbedPane1.addTab("Logar", jPanel2);

        jPanel3.setLayout(null);

        passwordSingUp_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        passwordSingUp_lbl.setForeground(new java.awt.Color(255, 255, 255));
        passwordSingUp_lbl.setText("Senha:");
        jPanel3.add(passwordSingUp_lbl);
        passwordSingUp_lbl.setBounds(10, 460, 70, 30);

        addressSingUp_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addressSingUp_lbl.setForeground(new java.awt.Color(255, 255, 255));
        addressSingUp_lbl.setText("Endereco:");
        jPanel3.add(addressSingUp_lbl);
        addressSingUp_lbl.setBounds(10, 410, 110, 30);

        emailSingUp_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emailSingUp_lbl.setForeground(new java.awt.Color(255, 255, 255));
        emailSingUp_lbl.setText("Email:");
        jPanel3.add(emailSingUp_lbl);
        emailSingUp_lbl.setBounds(10, 360, 70, 30);

        cpfSingUp_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cpfSingUp_lbl.setForeground(new java.awt.Color(255, 255, 255));
        cpfSingUp_lbl.setText("CPF:");
        jPanel3.add(cpfSingUp_lbl);
        cpfSingUp_lbl.setBounds(10, 260, 70, 30);

        nameSingUp_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nameSingUp_lbl.setForeground(new java.awt.Color(255, 255, 255));
        nameSingUp_lbl.setText("Nome:");
        jPanel3.add(nameSingUp_lbl);
        nameSingUp_lbl.setBounds(10, 310, 70, 30);

        showPassword_btn1.setBackground(new java.awt.Color(255, 255, 255));
        showPassword_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/eyeIcon.png"))); // NOI18N
        showPassword_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassword_btn1ActionPerformed(evt);
            }
        });
        jPanel3.add(showPassword_btn1);
        showPassword_btn1.setBounds(310, 460, 60, 30);

        sendSingUp_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sendSingUp_btn.setText("CADASTRAR");
        sendSingUp_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendSingUp_btnActionPerformed(evt);
            }
        });
        jPanel3.add(sendSingUp_btn);
        sendSingUp_btn.setBounds(100, 510, 200, 30);

        exit_btn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exit_btn1.setText("SAIR");
        exit_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btn1ActionPerformed(evt);
            }
        });
        jPanel3.add(exit_btn1);
        exit_btn1.setBounds(270, 630, 110, 30);

        nameSignUp_txt.setText("NOME COMPLETO");
        nameSignUp_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameSignUp_txtActionPerformed(evt);
            }
        });
        jPanel3.add(nameSignUp_txt);
        nameSignUp_txt.setBounds(110, 310, 260, 30);

        passwordSignUp_txt.setText("SENHA");
        passwordSignUp_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordSignUp_txtActionPerformed(evt);
            }
        });
        jPanel3.add(passwordSignUp_txt);
        passwordSignUp_txt.setBounds(110, 460, 190, 30);

        addressSignUp_txt.setText("ENDERECO");
        jPanel3.add(addressSignUp_txt);
        addressSignUp_txt.setBounds(110, 410, 260, 30);

        emailSignUp_txt.setText("EMAIL");
        jPanel3.add(emailSignUp_txt);
        emailSignUp_txt.setBounds(110, 360, 260, 30);

        cpfSignUp_txt.setText("CPF");
        jPanel3.add(cpfSignUp_txt);
        cpfSignUp_txt.setBounds(110, 260, 260, 30);

        setUpBG_lbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/SplashScreenRealHeroes2.png"))); // NOI18N
        jPanel3.add(setUpBG_lbl1);
        setUpBG_lbl1.setBounds(0, -10, 400, 700);

        jTabbedPane1.addTab("Cadastrar", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(396, 704));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        Model.Funcs_DAO.exit();
    }//GEN-LAST:event_exit_btnActionPerformed

    private void exit_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btn1ActionPerformed
        Model.Funcs_DAO.exit();
    }//GEN-LAST:event_exit_btn1ActionPerformed

    private void sendSingUp_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendSingUp_btnActionPerformed
        String cpf = cpfSignUp_txt.getText();
        String name = nameSignUp_txt.getText();
        String email = emailSignUp_txt.getText();
        String address = addressSignUp_txt.getText();
        String password = passwordSignUp_txt.getText();
        if (Model.TutorFuncs_DAO.signUp(cpf, name, email, address, password)) {
            Model.Funcs_DAO.changeScreen(this, new MainTutorMenu_GUI());
        }
    }//GEN-LAST:event_sendSingUp_btnActionPerformed

    private void passwordSignUp_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordSignUp_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordSignUp_txtActionPerformed

    private void nameSignUp_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameSignUp_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameSignUp_txtActionPerformed

    private void passwordLogin_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordLogin_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordLogin_txtActionPerformed

    private void sendLogin_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendLogin_btnActionPerformed
        String cpf = cpfLogin_txt.getText();
        String password = passwordLogin_txt.getText();
        if (Model.Login_DAO.login(cpf, password)) {
            Model.Funcs_DAO.changeScreen(this, new MainTutorMenu_GUI());
        }
    }//GEN-LAST:event_sendLogin_btnActionPerformed

    private void showPassword_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassword_btnActionPerformed
        if (showPassword_btn.isSelected()) {
            // Mostrar os caracteres reais
            passwordLogin_txt.setEchoChar('\0');
        } else {
            // Ocultar os caracteres reais
            passwordLogin_txt.setEchoChar('\u25cf'); 
        }
    }//GEN-LAST:event_showPassword_btnActionPerformed

    private void showPassword_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassword_btn1ActionPerformed
        if (showPassword_btn1.isSelected()) {
            // Mostrar os caracteres reais
            passwordSignUp_txt.setEchoChar('\0');
        } else {
            // Ocultar os caracteres reais
            passwordSignUp_txt.setEchoChar('\u25cf'); 
        }
    }//GEN-LAST:event_showPassword_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetUp_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetUp_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetUp_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetUp_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetUp_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField addressSignUp_txt;
    private javax.swing.JLabel addressSingUp_lbl;
    private javax.swing.JLabel cpfLogin_lbl;
    public static javax.swing.JTextField cpfLogin_txt;
    public static javax.swing.JTextField cpfSignUp_txt;
    private javax.swing.JLabel cpfSingUp_lbl;
    public static javax.swing.JTextField emailSignUp_txt;
    private javax.swing.JLabel emailSingUp_lbl;
    public static javax.swing.JButton exit_btn;
    public static javax.swing.JButton exit_btn1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTextField nameSignUp_txt;
    private javax.swing.JLabel nameSingUp_lbl;
    private javax.swing.JLabel passwordLogin_lbl;
    public static javax.swing.JPasswordField passwordLogin_txt;
    public static javax.swing.JPasswordField passwordSignUp_txt;
    private javax.swing.JLabel passwordSingUp_lbl;
    public static javax.swing.JButton sendLogin_btn;
    public static javax.swing.JButton sendSingUp_btn;
    private javax.swing.JLabel setUpBG_lbl;
    private javax.swing.JLabel setUpBG_lbl1;
    private javax.swing.JToggleButton showPassword_btn;
    private javax.swing.JToggleButton showPassword_btn1;
    // End of variables declaration//GEN-END:variables
}
